# Generated by Django 5.2.8 on 2025-11-27 06:13

from django.db import migrations

def create_conductores(apps, schema_editor):
    Conductor = apps.get_model('delivery', 'Conductor')
    for i in range(1, 6):
        Conductor.objects.create(nombre=f'Conductor {i}')

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_conductores),
    ]
