# Generated by Django 5.2.8 on 2025-11-29 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20251127_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.conductor'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
