# Generated by Django 5.2.8 on 2025-11-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_conductor_fcm_token_alter_ubicacion_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='longitud',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='coordenadas',
            field=models.CharField(blank=True, help_text='Formato: lat,lng', max_length=100, null=True),
        ),
    ]
