# Generated by Django 5.2.8 on 2025-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_ubicacion_latitud_remove_ubicacion_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='con_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
