# Generated by Django 5.2.8 on 2025-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_conductor_con_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
