# Generated by Django 5.2.8 on 2025-11-29 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_conductor_fcm_token_alter_ubicacion_conductor_and_more'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='delivery.conductor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='conductores_rechazados',
            field=models.ManyToManyField(blank=True, related_name='pedidos_rechazados', to='delivery.conductor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('buscando', 'Buscando Conductor'), ('aceptado', 'Aceptado'), ('recibido', 'Recibido por Conductor'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25),
        ),
        migrations.AddField(
            model_name='pedido',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
