# Generated by Django 5.2.8 on 2025-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_conductor_pedido_conductores_rechazados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
