# Generated by Django 5.2.8 on 2025-11-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_latitud_pedido_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='longitud',
        ),
        migrations.AddField(
            model_name='pedido',
            name='coordenadas',
            field=models.CharField(blank=True, help_text='Formato: lat,lng', max_length=100, null=True),
        ),
    ]
