# Generated by Django 5.2.8 on 2025-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedido_latitud_remove_pedido_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('buscando', 'Buscando Conductor'), ('aceptado', 'Aceptado'), ('recibido', 'Recibido por Conductor'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('disponible', 'Disponible para todos')], default='pendiente', max_length=25),
        ),
    ]
