# Generated by Django 5.0.6 on 2025-11-30 07:43

from django.db import migrations

def create_default_restaurant(apps, schema_editor):
    Restaurante = apps.get_model('restaurante', 'Restaurante')
    Restaurante.objects.create(
        nombre='KingsFood',
        coordenadas='-17.783306,-63.182139'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_restaurant),
    ]
